### ISSUE TITLE
怎么执行JavaScript脚本

### ISSUE THREAD

**Issue by wrhcute** [clicknium/clicknium-docs#45]
你好 怎么执行JavaScript脚本，为什么没有示例，调用 execute_js方法执行一直是不成功的

**Comment by yongjuntian** [comment]
can you share your execute_js code and what 's the error?
you can take a look at the example on official api doc to see whether it is helpful
https://www.clicknium.com/documents/references/python/webdriver/browser/browsertab/webelement/execute_js
