### ISSUE TITLE
cc.edge.browsers memory leak

### ISSUE THREAD

**Issue by CzakuGim** [clicknium/clicknium-docs#46]
Hello,
I'm using the clicknium in some of my projects and I have found something disturbing there. To show this I have prepared some simple script like below:

```
    from clicknium import clicknium as cc
    from time import sleep

    if not cc.edge.extension.is_installed():
        cc.edge.extension.install_or_update()

    while True:
        cc.edge.browsers
        sleep(0.2)
```
Running this script will increase memory usage continuously.

Same if I will use script below:

```
      from clicknium import clicknium as cc

      if not cc.edge.extension.is_installed():
          cc.edge.extension.install_or_update()

      cc_browsers = cc.edge.browsers
      while True:
          for browser in cc_browsers:
              for tab in browser.tabs:
                  print(tab.title)
```
Could you give me any update about this?

Have a nice day!

**Comment by yongjuntian** [comment]
thanks for the feedback, we will reproduce this issue and update about this.

**Comment by kayYOLO** [comment]
SDK and plugin version mismatch.

**Comment by kayYOLO** [comment]
SDK and plugin version mismatch.
