### ISSUE TITLE
希望出一个教程文档，讲清楚录制器的参数

### ISSUE THREAD

**Issue by tywilsonsky** [clicknium/clicknium-docs#47]
我发现不同电脑录制器录制同一个软件，会出现不同参数，无法准备适配所有电脑（都是windonws），网上找不到更多的信息，不会使用了

**Comment by kayYOLO** [comment]
可以采用[Recapture&compare](https://www.clicknium.com/documents/tutorial/recorder/recapture&compare)，对比参数差异。 
然后参考 [Make locator generalized and stable](https://www.clicknium.com/documents/tutorial/locator#make-locator-generalized-and-stable)采用参数或者Wildcard来调整locator参数进行泛化。
