### ISSUE TITLE
clicknium.send_text does not support str with "+"?

### ISSUE THREAD

**Issue by phoenixor** [clicknium/clicknium-docs#50]
i use clicknium for windows desktop software called wxworklocal, like QQ. When working with the password, i found it can not input the correct password, It always miss one letter, i thought it's because my password has symbol "+" in it. But when i input password manually, it's correct. 
How can i fix this bug? I've looking for the document but found nothing
![image](https://user-images.githubusercontent.com/6568115/204126840-6d82e5e9-f5bc-4a34-9bf8-3e5e6ed0fd16.png)

**Comment by kayYOLO** [comment]
Thanks for the feedback. We will try to reproduce this issue. Did you try to turn your input method to English?
