### ISSUE TITLE
Can it run in the background?

### ISSUE THREAD

**Issue by RoseRuner** [clicknium/clicknium-docs#57]
**运行环境**

- 操作系统：Windows 11 专业版 22H2
- VS Code：1.77.3
- Python：3.11.2
- clicknium-module：0.1.14

**问题描述**
是否能够使自动化在后台运行，目前运行后，点击其他窗口，会一直弹回到Edge浏览器，影响其他工作进行。

**Comment by kayYOLO** [comment]
可以使用headless mode: https://www.clicknium.com/documents/how-to/how-to-headless
